# Copyright (c) 2026, afmcoltd

WORKFLOWS = (
    "Custody Damage Assessment Workflow",
    "Dispatch Trip Workflow",
    "Driver Clearance Workflow",
    "Fuel Claim Workflow",
    "Fuel Exception Case Workflow",
    "Fuel Request Workflow",
    "Lease Workflow",
    "Maintenance Request Workflow",
    "Movement Cost Recovery Workflow",
    "Movement Cost Transfer Workflow",
    "Rental Settlement Workflow",
    "Route Assignment Workflow",
    "Salis Payment Request Workflow",
    "Subcontractor Service Contract Workflow",
    "Transport Request Workflow",
    "Utility Bill Entry Workflow",
    "Vehicle Damage Write-Off Workflow",
    "Vehicle Incident Workflow",
)

WORKFLOW_STATES = (
    "Acknowledged",
    "Active",
    "Approved",
    "Approved by Finance",
    "Blocked",
    "Cancelled",
    "Cleared",
    "Closed",
    "Completed",
    "Dispatched",
    "Disputed",
    "Done",
    "Draft",
    "Evidence Required",
    "Expired",
    "Failed",
    "Fulfilled",
    "In Progress",
    "New",
    "Open",
    "Paid",
    "Pending",
    "Pending Approval",
    "Pending Finance",
    "Planned",
    "Posted (memo)",
    "Reconciled",
    "Recovered",
    "Rejected",
    "Resolved",
    "Reverted",
    "Scheduled",
    "Submitted to Movement",
    "Terminated",
    "Under Investigation",
    "Under Review",
    "Validated",
    "Waived",
)

WORKFLOW_ACTIONS = (
    "Acknowledge",
    "Activate",
    "Approve",
    "Approve (Finance)",
    "Authorize (Operations)",
    "Authorize (Regional)",
    "Block",
    "Cancel",
    "Clear",
    "Close",
    "Complete",
    "Confirm Fulfilment",
    "Dispatch",
    "Dispute",
    "Mark Failed",
    "Mark Paid",
    "Post (memo)",
    "Re-reconcile",
    "Re-submit",
    "Reconcile",
    "Recover",
    "Reject",
    "Reopen",
    "Request Evidence",
    "Resolve",
    "Resume Investigation",
    "Revert",
    "Revise",
    "Schedule",
    "Start Investigation",
    "Start Processing",
    "Submit for Approval",
    "Submit for Review",
    "Submit to Finance",
    "Submit to Movement",
    "Terminate",
    "Validate",
    "Waive",
)
