/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Brand: typeof import('./src/components/Brand.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    ErrorState: typeof import('./src/components/ErrorState.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    LangToggle: typeof import('./src/components/LangToggle.vue')['default']
    LoadingState: typeof import('./src/components/LoadingState.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Unlinked: typeof import('./src/components/Unlinked.vue')['default']
  }
}
