/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BoardingPanel: typeof import('./src/components/BoardingPanel.vue')['default']
    DriverMap: typeof import('./src/components/DriverMap.vue')['default']
    RoutePanel: typeof import('./src/components/RoutePanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
