/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BuildingPicker: typeof import('./src/components/BuildingPicker.vue')['default']
    CadenceSection: typeof import('./src/components/CadenceSection.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    LangToggle: typeof import('./src/components/LangToggle.vue')['default']
    ProgressRing: typeof import('./src/components/ProgressRing.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskRow: typeof import('./src/components/TaskRow.vue')['default']
  }
}
