/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BoardingFlow: typeof import('./src/components/BoardingFlow.vue')['default']
    BoardingPass: typeof import('./src/components/BoardingPass.vue')['default']
    BoardingPassOverlay: typeof import('./src/components/BoardingPassOverlay.vue')['default']
    Brand: typeof import('./src/components/Brand.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    LangToggle: typeof import('./src/components/LangToggle.vue')['default']
    PullIndicator: typeof import('./src/components/PullIndicator.vue')['default']
    QrCode: typeof import('./src/components/QrCode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('./src/components/Skeleton.vue')['default']
    TripProgressBar: typeof import('./src/components/TripProgressBar.vue')['default']
    TripRating: typeof import('./src/components/TripRating.vue')['default']
  }
}
