/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertDrawer: typeof import('./src/components/AlertDrawer.vue')['default']
    FleetCardGrid: typeof import('./src/components/FleetCardGrid.vue')['default']
    FleetDriverLens: typeof import('./src/components/FleetDriverLens.vue')['default']
    FleetSidebar: typeof import('./src/components/FleetSidebar.vue')['default']
    FleetTable: typeof import('./src/components/FleetTable.vue')['default']
    FleetToolbar: typeof import('./src/components/FleetToolbar.vue')['default']
    FleetTopbar: typeof import('./src/components/FleetTopbar.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    LangToggle: typeof import('./src/components/LangToggle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    VehiclePanel: typeof import('./src/components/VehiclePanel.vue')['default']
  }
}
